<a href="https://colab.research.google.com/github/manhnt2115/TH_DeepLearning/blob/main/DeepLearning(ChieuT2)(20_04)(Lab1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy
import numpy as np
my_list = [1,9,15,39]
print("Python list:",my_list)
my_numpy_array=np.array(my_list)
print("Numpy array:",my_numpy_array)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]


In [3]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [4]:
d=np.array([
    [[1.,2.,3.],[4.,5.,6]],
    [[7.,8.,9],[10.,11.,12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [5]:
e=np.zeros((2,3))
f=np.ones((3,3))
print('Zero matrix:\n',e)
print('One matrix:\n',f)

Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
e=np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f=e.reshape(3,2)
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6]],
            [[7.,8.,9],[10.,11.,12]]
            ])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape (3,4)\n',h)
j=g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k=g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


TypeError: 'tuple' object is not callable