<a href="https://colab.research.google.com/github/manhnt2115/TH_DeepLearning/blob/main/DeepLearning(ChieuT2)(20_04)(Lab1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy
import numpy as np
my_list = [1,9,15,39]
print("Python list:",my_list)
my_numpy_array=np.array(my_list)
print("Numpy array:",my_numpy_array)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]


In [3]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [4]:
d=np.array([
    [[1.,2.,3.],[4.,5.,6]],
    [[7.,8.,9],[10.,11.,12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [5]:
e=np.zeros((2,3))
f=np.ones((3,3))
print('Zero matrix:\n',e)
print('One matrix:\n',f)

Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
e=np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f=e.reshape(3,2)
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6]],
            [[7.,8.,9],[10.,11.,12]]
            ])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape (3,4)\n',h)
j=g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k=g.reshape(2,3,2)
print('reshape (2,3,2)\n',k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [8]:
e=np.array([[1.,2.,3.],[4.,5.,6]])
f=e.flatten()
print(f)
g=np.array([[[1.,2.,3],[4.,5.,6]],
            [[7.,8.,9],[10.,11.,12]]
            ])
j=g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [9]:
f=np.array([1.,2.,3.])
g=np.array([4.,5.,6.])
h_stack=np.hstack((f,g))
print('Horizontal Append\n',h_stack)
v_stack=np.vstack((f,g))
print('Vertical Append\n',v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [10]:
a=np.random.randint(100,size=(5,))
print("Random 1-D array \n ",a)
b=np.random.randint(100,size=(3,4))
print("Random 2-D array \n",b)
c=np.random.randint(100,size=(3,4,3))
print("Random 3-D array \n",c)

Random 1-D array 
  [53  2 37 51 44]
Random 2-D array 
 [[49 77 42  4]
 [56 59 79  8]
 [92 77 11 68]]
Random 3-D array 
 [[[82 87 54]
  [ 7 34 90]
  [53 67 66]
  [10  0 74]]

 [[ 5 19 31]
  [59 93 45]
  [45 72 92]
  [55  1 87]]

 [[ 4  8 99]
  [50 43 35]
  [38 79 75]
  [74 70 26]]]


In [11]:
a=np.random.normal(5,0.5,10)
print(a)
print(np.mean(a))
print(np.std(a))
print(np.var(a))

[4.73453334 4.71861737 4.96997408 4.64969206 4.94889115 4.45738936
 4.85735907 5.29009828 4.87083891 4.65102864]
4.814842226083488
0.21689568793619654
0.04704373944531595


In [12]:
a=np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)
b=np.random.choice([2,4,6,8,10,12,14,16,18,20],size=(3,5))
print(b)

18
[[14 10 16  2 14]
 [14  8 18 18  4]
 [18  2 10 14 16]]


In [13]:
A=np.matrix(np.ones(((5,5))))
print('The matrix\n',A)
np.array(A)[2]=2
print('Change values of third row with array\n',A)
np.asarray(A)[2]=2
print('Change values of third row with asarray\n',A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
a=np.arange(1,20)
print(a)
b=np.arange(1,20,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [15]:
a=np.linspace(1.,5.,num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [16]:
a=np.array([(1,2,3),(4,5,6)])
print(a)
print('first row:',a[0])
print('second row:',a[1])
print('Second column:',a[:,1])
print('First column:',a[:,0])
print('First two values of second row:',a[1,:2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
First column: [1 4]
First two values of second row: [4 5]
